# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeStatsActor <- function(int_effects, rs, actors, edgelist, adj_mat, covariates, interact_effects, scaling, statprevmat) {
    .Call(`_remulate_computeStatsActor`, int_effects, rs, actors, edgelist, adj_mat, covariates, interact_effects, scaling, statprevmat)
}

computeStatsTie <- function(int_effects, rs, actors, edgelist, adj_mat, covariates, interact_effects, scaling, mem_start, mem_end, statprevmat) {
    .Call(`_remulate_computeStatsTie`, int_effects, rs, actors, edgelist, adj_mat, covariates, interact_effects, scaling, mem_start, mem_end, statprevmat)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_remulate_RcppExport_registerCCallable`)
})
