# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

standardize <- function(statrow) {
    .Call(`_remulate_standardize`, statrow)
}

compute_stats <- function(int_effects, P, rs, actors, edgelist, adj_mat, covariates, scaling, statprevmat) {
    .Call(`_remulate_compute_stats`, int_effects, P, rs, actors, edgelist, adj_mat, covariates, scaling, statprevmat)
}

